name: Exécution manuelle de app.py

on:
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  run-script:
    runs-on: ubuntu-latest
    environment: variable

    steps:
      - uses: actions/checkout@v3

      - name: Installation de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installation des dépendances
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Exécution du script
        run: python waker.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # ✅ jeton auto fourni par GitHub
          CLE_ULTRA: ${{ secrets.CLE_ULTRA }}
          URL: ${{ vars.URL }}