name: Exécution automatique de app.py

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    environment: variable   # ⬅️ ici ton environment personnalisé !

    steps:
      - uses: actions/checkout@v3

      - name: Installation de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installation des dépendances
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Exécution du script
        run: python app.py
        env:
          CLE_ULTRA: ${{ secrets.CLE_ULTRA }}
          URL: ${{ vars.URL }}